bind 0.0.0.0
port 6379
protected-mode yes
tcp-keepalive 60
timeout 0
maxclients 10000

appendonly yes
appendfsync everysec
auto-aof-rewrite-percentage 100
auto-aof-rewrite-min-size 64mb

save 900 1
save 300 10
save 60 10000

dir /data
dbfilename dump.rdb

maxmemory-policy noeviction

loglevel notice
logfile ""

slowlog-log-slower-than 10000
slowlog-max-len 128
