// Wrapper script the plugin emits as a second asset key. The
// statefulset is configured to exec this script as its command;
// the script reads VOODU_REPLICA_ORDINAL (set by the controller
// per-pod) + REDIS_MASTER_ORDINAL (config bucket var, default 0)
// and decides at boot whether THIS pod is the master or a replica.
//
// Why a wrapper script and not a templated `command`:
//
//   - The same redis.conf serves all pods (one asset, N consumers).
//     If the role lived in the conf, every replica would need a
//     different conf and the asset fan-out becomes N-deep.
//   - replicaof is a runtime flag, not a directive — passing it
//     via `redis-server --replicaof host port` is the documented
//     non-conf path. The wrapper picks the args; the conf stays
//     pure plugin-managed bytes.
//   - Failover (M2.2 future) flips REDIS_MASTER_ORDINAL via
//     `vd config set` then runs `vd apply` to roll the
//     statefulset. The new role takes effect on next start
//     without the operator having to write a per-pod manifest.
//
// The script is dependency-light (sh, no bash) so it works in
// the bare redis:7-alpine image without extra packages.

package main

import "strings"

// entrypointAssetKey is the key the asset manifest uses for the
// wrapper script. Lives alongside redis_conf in the same asset
// file map so a single asset reference resolves both — the
// statefulset's volumes list mounts each via its own ${asset.X.Y.K}
// reference at the right path.
const entrypointAssetKey = "entrypoint"

// entrypointMountPath is where the wrapper lands inside the
// container. /usr/local/bin is on PATH for redis:7-alpine and
// is the conventional spot for site-installed scripts; using
// it means `voodu-redis-entrypoint` works as a bare command.
const entrypointMountPath = "/usr/local/bin/voodu-redis-entrypoint"

// The wrapper script template. ${name}.${scope}.voodu is the
// FQDN convention voodu0 resolves; the script substitutes the
// scope/name at apply time so each plugin invocation embeds the
// instance-specific master FQDN directly. (Redis's `--replicaof`
// flag wants the host as a literal — there's no env-var
// indirection in the redis-server CLI.)
//
// Substitution markers:
//
//	__REPLICA_HOST_PREFIX__   → name
//	__REPLICA_HOST_SUFFIX__   → ".<scope>.voodu" (or ".voodu" unscoped)
//
// At runtime the only choice the script makes is "am I the master
// or a replica" via VOODU_REPLICA_ORDINAL vs REDIS_MASTER_ORDINAL.
const entrypointScriptTemplate = `#!/bin/sh
# voodu-redis entrypoint — picks master vs replica role at boot.
# Generated by voodu-redis plugin. Do not edit in place; the
# plugin re-emits this asset on every apply.
set -eu

ORDINAL="${VOODU_REPLICA_ORDINAL:-0}"
MASTER_ORDINAL="${REDIS_MASTER_ORDINAL:-0}"

CONF=/etc/redis/redis.conf

if [ "$ORDINAL" = "$MASTER_ORDINAL" ]; then
    # Master: run with the conf as-is. The conf already declares
    # replica-read-only, replica-serve-stale-data, etc. — those
    # are no-ops on a master and become active if THIS pod is
    # ever demoted to a replica via a REDIS_MASTER_ORDINAL flip.
    echo "voodu-redis: starting as MASTER (ordinal=$ORDINAL)" >&2
    exec redis-server "$CONF"
fi

# Replica: dial master at the deterministic per-pod FQDN voodu0
# resolves (` + "`<name>-<n>.<scope>.voodu`" + `). Auth carried by
# the masterauth directive in redis.conf — no env-var password
# leakage on the command line.
MASTER_HOST=__REPLICA_HOST_PREFIX__-${MASTER_ORDINAL}__REPLICA_HOST_SUFFIX__
echo "voodu-redis: starting as REPLICA (ordinal=$ORDINAL) targeting $MASTER_HOST:6379" >&2
exec redis-server "$CONF" --replicaof "$MASTER_HOST" 6379
`

// renderEntrypointScript materialises the script template for a
// specific (scope, name). The host prefix/suffix wrap around the
// ordinal so the shell var ${MASTER_ORDINAL} substitutes inside
// the FQDN at runtime — `<name>-0.<scope>.voodu`, `<name>-1.<scope>.voodu`,
// etc. Unscoped statefulsets get `<name>-N.voodu`.
//
// Pure function (no IO) so cmdExpand can call it deterministically
// — same (scope, name) → same bytes → same asset digest → no
// spurious rolling restart on replays.
func renderEntrypointScript(scope, name string) string {
	suffix := ".voodu"
	if scope != "" {
		suffix = "." + scope + ".voodu"
	}

	out := entrypointScriptTemplate
	out = strings.ReplaceAll(out, "__REPLICA_HOST_PREFIX__", name)
	out = strings.ReplaceAll(out, "__REPLICA_HOST_SUFFIX__", suffix)

	return out
}
