// Sentinel-mode entrypoint + conf renderers.
//
// Same shape as the data-redis entrypoint flow (entrypoint.go) —
// asset carries TWO files, one is bootstrap config, the other is
// a sh wrapper that materialises the runtime config from env then
// execs the redis binary in the right mode.
//
// Why a wrapper instead of a static sentinel.conf:
//
//   - Quorum is derived from `replicas` at expand time but the
//     wrapper handles it at boot so the asset doesn't churn when
//     replicas count changes (the conf bytes stay parametric).
//   - The MASTER ordinal is read from VOODU_MASTER_ORDINAL_INITIAL
//     env (set by the plugin from the target's REDIS_MASTER_ORDINAL
//     config bucket at expand time). Sentinel auto-discovers the
//     true topology via INFO replication on first connect, so a
//     stale initial value self-heals within seconds — but starting
//     from the recorded value avoids the brief monitoring-wrong-
//     pod window after a sentinel pod restart post-failover.
//   - The failover hook script path is conventionally set to
//     /usr/local/bin/voodu-sentinel-failover-hook, which the
//     entrypoint also writes. M-S2 replaces the stub body of that
//     hook with the real `vd redis:failover --no-restart` callback.
package main

import (
	"fmt"
	"strings"
)

const (
	// Asset keys for the sentinel-mode pair. Distinct from the
	// data-redis asset keys (redis_conf, entrypoint) so a future
	// "single resource hosts both" architecture can coexist; for
	// now the plugin emits one or the other, never both.
	sentinelEntrypointAssetKey = "sentinel_entrypoint"
	sentinelHookAssetKey       = "sentinel_hook"

	// Mount paths — /usr/local/bin is on PATH for redis:7-alpine
	// and redis:8 alike, the conventional spot for site scripts.
	sentinelEntrypointMountPath = "/usr/local/bin/voodu-sentinel-entrypoint"
	sentinelHookMountPath       = "/usr/local/bin/voodu-sentinel-failover-hook"

	// Persistent state dir — sentinel's runtime sentinel.conf lives
	// here and survives pod recreation via volume_claim. Lets
	// sentinels remember discovered peers + replicas across
	// restarts, recovering from "master was down at sentinel boot"
	// scenarios.
	sentinelStateDir  = "/var/lib/sentinel"
	sentinelStatePath = "/var/lib/sentinel/sentinel.conf"

	// Sentinel listens on its own dedicated port — operators who
	// link the sentinel resource to a consumer expect 26379 by
	// muscle memory (Redis Sentinel default).
	sentinelPort = 26379

	// Master name in sentinel.conf. Hard-coded — operators don't
	// configure this because it's an INTERNAL identifier sentinel
	// uses to refer to the monitored master in commands like
	// `SENTINEL FAILOVER mymaster`. The link command emits
	// REDIS_MASTER_NAME=mymaster so consumers using a sentinel-
	// aware client know what to ask for.
	sentinelMasterName = "mymaster"
)

// renderSentinelEntrypointScript produces the sh wrapper the
// sentinel statefulset execs as its command. The wrapper:
//
//  1. Reads VOODU_MONITOR_SCOPE / VOODU_MONITOR_NAME (set by the
//     plugin from the HCL `monitor = "scope/name"` field).
//  2. Reads VOODU_REDIS_REPLICAS (set by plugin from the sentinel
//     resource's replicas count) and computes quorum (half+1).
//  3. Reads REDIS_MASTER_ORDINAL via env_from from the monitor
//     target's bucket (default 0 if absent).
//  4. Materialises the failover hook script with chmod +x — Redis
//     refuses to start sentinel if client-reconfig-script isn't
//     executable, and asset-mounted files come in 0644 read-only.
//     Embedding the hook inline + chmod sidesteps the bind-mount
//     mode constraint with one fewer asset file.
//  5. Composes the master FQDN against voodu0's DNS scheme.
//  6. Writes /etc/sentinel/sentinel.conf with substitutions and
//     execs redis-sentinel against it.
//
// Pure function — same inputs always produce the same bytes, so
// the asset digest stays stable across replays.
func renderSentinelEntrypointScript() string {
	hookBody := renderSentinelHookScript()

	return `#!/bin/sh
# voodu-redis sentinel entrypoint — composes /etc/sentinel/sentinel.conf
# from env at boot then execs redis-sentinel. Generated by the
# voodu-redis plugin (do not edit; re-emitted on every apply).
set -eu

# Materialise the failover hook with chmod +x. We can't mount it
# from the asset because asset bind-mounts come in 0644 read-only,
# and Redis refuses to start sentinel when client-reconfig-script
# isn't executable. Writing the script inline at boot sidesteps
# the bind-mount mode constraint AND removes one asset key.
#
# Quoted heredoc (<<'__VOODU_HOOK_END__') preserves $1, $2,
# $VOODU_CONTROLLER_URL etc. as LITERAL characters in the output
# file — they get expanded when sentinel exec's the hook later,
# not now during entrypoint init.
cat > ` + sentinelHookMountPath + ` <<'__VOODU_HOOK_END__'
` + hookBody + `__VOODU_HOOK_END__
chmod +x ` + sentinelHookMountPath + `

# Required env from the plugin (set in the statefulset spec):
: "${VOODU_MONITOR_SCOPE:?missing VOODU_MONITOR_SCOPE (set by plugin from monitor field)}"
: "${VOODU_MONITOR_NAME:?missing VOODU_MONITOR_NAME (set by plugin from monitor field)}"
: "${VOODU_REDIS_REPLICAS:?missing VOODU_REDIS_REPLICAS (set by plugin from replicas field)}"

# REDIS_MASTER_ORDINAL flows in via env_from from the monitor
# target's config bucket. Default to 0 if absent (first apply,
# data redis pre-failover) — sentinel's INFO replication self-
# corrects within seconds if 0 isn't actually master right now.
MASTER_ORDINAL="${REDIS_MASTER_ORDINAL:-0}"

# Quorum = (replicas / 2) + 1 — integer math via shell expansion.
# Matches the formula validated at expand time in sentinel.go.
QUORUM=$(( VOODU_REDIS_REPLICAS / 2 + 1 ))

# M-S4 boot-time preflight: confirm the monitor target exists in
# the voodu store. Catches the most common operator typo (wrong
# scope/name in the HCL) before sentinel starts spamming
# "master unreachable" logs every monitor cycle.
#
# Best-effort: when VOODU_CONTROLLER_URL is unset (no callback
# plumbing in this deployment), we skip the check and trust
# sentinel to surface misconfiguration via its own logs.
#
# Cascade detection (target itself being a sentinel) is NOT
# done here — JSON parsing in pure /bin/sh would balloon this
# script. Sentinel's own logs surface that case clearly: dialing
# port 6379 against a sentinel pod (which listens on 26379) gets
# "connection refused" forever. Operator sees the pattern, checks
# the monitor field.
#
# Non-fatal: missing target might be transient (apply-order race
# on first deploy, slow first boot). Sentinel tolerates an
# unreachable master at startup and reconnects.
if [ -n "${VOODU_CONTROLLER_URL:-}" ]; then
    DESCRIBE_URL="${VOODU_CONTROLLER_URL%/}/describe?kind=statefulset&scope=${VOODU_MONITOR_SCOPE}&name=${VOODU_MONITOR_NAME}"

    if wget -q -O /dev/null "$DESCRIBE_URL" 2>/dev/null; then
        echo "voodu-sentinel: preflight OK — monitor target ${VOODU_MONITOR_SCOPE}/${VOODU_MONITOR_NAME} exists in voodu store" >&2
    else
        echo "voodu-sentinel: WARNING — monitor target ${VOODU_MONITOR_SCOPE}/${VOODU_MONITOR_NAME} not found in voodu store (or controller unreachable). Sentinel will keep retrying; check the 'monitor' field in your HCL and confirm the data redis is applied." >&2
    fi
fi

# Master FQDN follows voodu0's DNS scheme: <name>-<ord>.<scope>.voodu.
# Unscoped statefulsets resolve as <name>-<ord>.voodu.
if [ -z "$VOODU_MONITOR_SCOPE" ]; then
    MASTER_HOST="${VOODU_MONITOR_NAME}-${MASTER_ORDINAL}.voodu"
else
    MASTER_HOST="${VOODU_MONITOR_NAME}-${MASTER_ORDINAL}.${VOODU_MONITOR_SCOPE}.voodu"
fi

CONF=` + sentinelStatePath + `
mkdir -p ` + sentinelStateDir + ` /etc/sentinel/conf.d

# Bootstrap-only-if-empty: persisted sentinel.conf survives pod
# restart so sentinels remember discovered peers + replicas (avoids
# the bootstrap deadlock when master is down at sentinel boot —
# without persistent state, sentinels can't discover peers via
# the master's pubsub, can't reach quorum, no failover).
#
# Empty/missing file → write fresh bootstrap.
# Existing non-empty file → use as-is, sentinel rewrites it at
# runtime with observed state.
#
# Operator-override .conf files at /etc/sentinel/conf.d/* are
# always re-included on every boot regardless of bootstrap state.
if [ ! -s "$CONF" ]; then
    echo "voodu-sentinel: persistent state empty, writing bootstrap conf to $CONF" >&2
    cat > "$CONF" <<EOF
port ` + fmt.Sprintf("%d", sentinelPort) + `
sentinel resolve-hostnames yes
sentinel announce-hostnames yes
sentinel monitor ` + sentinelMasterName + ` $MASTER_HOST 6379 $QUORUM
sentinel down-after-milliseconds ` + sentinelMasterName + ` 5000
sentinel failover-timeout ` + sentinelMasterName + ` 60000
sentinel parallel-syncs ` + sentinelMasterName + ` 1
sentinel client-reconfig-script ` + sentinelMasterName + ` ` + sentinelHookMountPath + `
include /etc/sentinel/conf.d/*.conf
EOF
else
    echo "voodu-sentinel: reusing persistent sentinel.conf at $CONF (preserves discovered peers/replicas across restart)" >&2
fi

# auth-pass is opt-in via REDIS_PASSWORD env (flows in via env_from
# from the monitor target's bucket). Written to the persistent
# conf only on first bootstrap to avoid appending duplicates on
# every restart. Password rotation post-bootstrap requires either
# a SENTINEL SET auth-pass via redis-cli OR a wipe of the
# persistent volume to re-bootstrap.
if [ -n "${REDIS_PASSWORD:-}" ] && ! grep -q "^sentinel auth-pass " "$CONF" 2>/dev/null; then
    echo "sentinel auth-pass ` + sentinelMasterName + ` $REDIS_PASSWORD" >> "$CONF"
fi

echo "voodu-sentinel: monitoring ${VOODU_MONITOR_SCOPE}/${VOODU_MONITOR_NAME} master=$MASTER_HOST:6379 quorum=$QUORUM (replicas=$VOODU_REDIS_REPLICAS)" >&2

# We exec redis-server with --sentinel rather than redis-sentinel
# directly. Two reasons:
#   1. The redis-sentinel binary is just a symlink to redis-server
#      with --sentinel baked in (Redis 2.8+) — same effect.
#   2. Some minimal redis images ship without the symlink.
#      redis-server is always present.
exec redis-server "$CONF" --sentinel
`
}

// renderSentinelHookScript produces the failover hook script
// that sentinel calls on +switch-master via the
// `client-reconfig-script` directive. M-S2 wires it through to
// `vd redis:failover --replica <new-ordinal> --no-restart` on
// the monitored target — the --no-restart flag tells voodu "the
// roles already moved inside Redis (sentinel did it), just
// sync the store so consumers' URLs refresh and crash-recovery
// boots pick the right role".
//
// Sentinel passes positional args (per Redis docs):
//
//	$1 master-name (e.g. "mymaster")
//	$2 role (leader|observer)
//	$3 state (start|end)
//	$4 from-ip
//	$5 from-port
//	$6 to-ip       — NEW master host (FQDN with resolve-hostnames yes)
//	$7 to-port
//
// We act on state=end (failover concluded). Three sentinels in
// the quorum each fire the script, so the controller sees up to
// 3 idempotent PUTs of the same value — that's the dedup-by-
// idempotency design from the M-S2 plan.
//
// The script needs the voodu controller URL. Read from
// VOODU_CONTROLLER_URL env (operator-supplied via HCL `env = {}`,
// or future plugin enhancement that injects it from the platform
// at expand time). When unset, we log and exit 0 — sentinel's
// auto-failover still completes the role flip inside Redis;
// only the voodu store stays stale until next operator gesture.
//
// Why exit 0 even on callback failure: sentinel treats non-zero
// from client-reconfig-script as a failed callback and may retry,
// but it doesn't undo the failover — so we'd just spam logs
// without changing outcomes. Exit 0 means "I've handled it as
// best I can"; the noisy log line is the audit trail.
func renderSentinelHookScript() string {
	return `#!/bin/sh
# voodu-redis sentinel failover hook — called by redis-sentinel
# via the client-reconfig-script directive on +switch-master.
# Generated by voodu-redis plugin (do not edit; re-emitted on
# every apply).
set -eu

MASTER_NAME="${1:-?}"
ROLE="${2:-?}"
STATE="${3:-?}"
FROM_IP="${4:-?}"
FROM_PORT="${5:-?}"
TO_IP="${6:-?}"
TO_PORT="${7:-?}"

echo "voodu-sentinel-hook: master=$MASTER_NAME role=$ROLE state=$STATE from=$FROM_IP:$FROM_PORT to=$TO_IP:$TO_PORT" >&2

# Only act on the "end" state — that's when the failover has
# fully completed and the new master is serving. The "start"
# event fires before promotion, when $TO_IP doesn't yet hold
# the new master. Acting on start would write a stale ordinal.
if [ "$STATE" != "end" ]; then
    exit 0
fi

# Required context — set by the plugin at expand time:
#   VOODU_MONITOR_SCOPE / VOODU_MONITOR_NAME → which redis to update
# Operator-supplied (or future plugin enhancement):
#   VOODU_CONTROLLER_URL → where to POST the callback
if [ -z "${VOODU_CONTROLLER_URL:-}" ]; then
    echo "voodu-sentinel-hook: VOODU_CONTROLLER_URL not set — store will be stale until next operator gesture" >&2
    exit 0
fi

# Extract the new master ordinal from the FQDN sentinel passed.
# With ` + "`sentinel resolve-hostnames yes`" + ` (set by the entrypoint),
# $TO_IP is "<name>-<ord>.<scope>.voodu" — we want the <ord>.
# Falls through to "0" on parse failure (degraded but not wrong:
# the operator can run a manual ` + "`vd redis:failover`" + ` to fix).
NEW_ORDINAL=$(echo "$TO_IP" | sed -nE 's/^[a-z0-9-]+-([0-9]+)\..*/\1/p')
if [ -z "$NEW_ORDINAL" ]; then
    echo "voodu-sentinel-hook: could not parse ordinal from to-ip=$TO_IP — store NOT updated" >&2
    exit 0
fi

TARGET="${VOODU_MONITOR_SCOPE}/${VOODU_MONITOR_NAME}"
URL="${VOODU_CONTROLLER_URL%/}/plugin/redis/failover"

# POST {"args":["<scope>/<name>","--replica","<N>","--no-restart"]}
# The --no-restart flag is THE point of this callback path: roles
# already moved inside Redis (that's what sentinel just did);
# we're just informing voodu so consumers' URLs refresh.
PAYLOAD=$(printf '{"args":["%s","--replica","%s","--no-restart"]}' "$TARGET" "$NEW_ORDINAL")

# Retry up to 5 times with exponential backoff. Sentinel fires
# this callback synchronously, so we keep total wall time bounded
# (~1+2+4+8+16 = 31s worst case). Beyond that, sentinel logs the
# slow callback but doesn't undo the failover.
ATTEMPT=0
SLEEP=1
while [ "$ATTEMPT" -lt 5 ]; do
    if wget -q -O /dev/null \
        --header="Content-Type: application/json" \
        --post-data="$PAYLOAD" \
        "$URL"; then
        echo "voodu-sentinel-hook: synced master ordinal=$NEW_ORDINAL to voodu store at $TARGET" >&2
        exit 0
    fi

    ATTEMPT=$((ATTEMPT + 1))
    echo "voodu-sentinel-hook: callback attempt $ATTEMPT failed, retrying in ${SLEEP}s" >&2
    sleep "$SLEEP"
    SLEEP=$((SLEEP * 2))
done

echo "voodu-sentinel-hook: gave up after 5 attempts; voodu store stale (ordinal=$NEW_ORDINAL not propagated to $TARGET)" >&2
exit 0
`
}

// composeSentinelDefaults is the sentinel-mode peer of
// composeDefaults. Same merge contract — operator-wins for
// declared keys, env deep-merges, volumes additive-merge.
//
// Defaults specific to sentinel mode:
//
//   - image: redis:7-alpine (sentinel ships in the same binary;
//     `redis-sentinel` is in PATH on this image)
//   - replicas: 3 (HA default; operator can override to 1 for
//     observer-only or 5+ for higher quorum)
//   - command: invoke the sh wrapper via `sh <path>` so the
//     asset's default 0644 mode is enough
//   - ports: 26379 (sentinel default)
//   - volumes: bind the entrypoint script from the asset; the
//     hook is embedded inline in the entrypoint and chmod'd at
//     boot (asset binds come 0644 read-only, breaks Redis)
//   - volume_claims: persistent /var/lib/sentinel for the
//     runtime sentinel.conf (see below)
//
// Why persistent sentinel.conf:
//
//   - Sentinels discover peers + replicas via pubsub on the
//     monitored master. If a sentinel boots while master is
//     DOWN (apply during incident, host reboot order race,
//     plugin upgrade with master GC'd in between), it can't
//     discover anything — gets stuck in +sdown solo, no
//     quorum, no failover.
//   - Persisting the runtime conf across pod restarts lets
//     sentinel remember peers + replicas from previous
//     successful runs, even if the master is unreachable on
//     this boot. Quorum + failover work as soon as 2 of 3
//     sentinels are up, regardless of master state.
//   - Sentinel itself rewrites the conf at runtime to record
//     observed topology. The volume claim makes those rewrites
//     survive pod recreation.
//
// Bootstrap-only-if-empty pattern: the entrypoint checks if
// /var/lib/sentinel/sentinel.conf already exists; if yes, uses
// it as-is (preserves discovered state); if no (first apply or
// volume wipe), writes the bootstrap directives and lets sentinel
// take it from there.
func composeSentinelDefaults(scope, name string) map[string]any {
	scopeRef := scope
	if scopeRef == "" {
		scopeRef = name
	}

	_ = scopeRef // reserved for future use (per-resource asset path

	return map[string]any{
		"image":    defaultImage,
		"replicas": 3,
		"command":  []any{"sh", sentinelEntrypointMountPath},
		"ports":    []any{fmt.Sprintf("%d", sentinelPort)},
		"volumes": []any{
			"${asset." + scope + "." + name + "." + sentinelEntrypointAssetKey + "}:" + sentinelEntrypointMountPath + ":ro",
		},
		"volume_claims": []any{
			map[string]any{
				"name":       "state",
				"mount_path": sentinelStateDir,
			},
		},
	}
}

// sentinelPodEnv builds the env map the plugin injects into the
// sentinel statefulset spec. These are READ by the entrypoint
// script at boot to compose sentinel.conf. Per-pod identity env
// (VOODU_REPLICA_ORDINAL, VOODU_SCOPE, etc.) and platform env
// (VOODU_CONTROLLER_URL) are added by the controller's pod env
// builders at runtime — those don't belong here.
//
// REDIS_PASSWORD and REDIS_MASTER_ORDINAL flow via env_from from
// the monitor target's bucket — see sentinelManifests.
func sentinelPodEnv(s *sentinelSpec, replicas int) map[string]any {
	scope, name, _ := splitMonitorRef(s.Monitor)

	return map[string]any{
		"VOODU_MONITOR_SCOPE":  scope,
		"VOODU_MONITOR_NAME":   name,
		"VOODU_REDIS_REPLICAS": fmt.Sprintf("%d", replicas),
	}
}

// mergeEnvFrom prepends operator-supplied env_from refs in front
// of the plugin-managed monitor ref. Operator's existing entries
// stack first (lowest priority), monitor-target's bucket layers
// last so its values win the conflict — same last-wins semantics
// jobs already have.
//
// Idempotent: re-emit on re-apply produces a stable list, no dup
// of the monitor ref. Operator-supplied env_from typed as []any
// (post-JSON-decode) becomes []string in the merged spec.
func mergeEnvFrom(operatorEnvFrom any, monitor string) []string {
	out := make([]string, 0, 4)

	if list, ok := operatorEnvFrom.([]any); ok {
		for _, v := range list {
			if s, ok := v.(string); ok && s != "" && s != monitor {
				out = append(out, s)
			}
		}
	}

	out = append(out, monitor)

	return out
}

// sentinelReplicas extracts the replica count for a sentinel
// resource. Defaults to 3 (HA minimum) when the operator omits
// it in sentinel mode — distinct from data-redis default of 1.
// Validated upstream by checkSentinelReplicas; this function
// trusts that constraint and just resolves the count.
func sentinelReplicas(operatorSpec map[string]any) int {
	raw, present := operatorSpec["replicas"]
	if !present {
		return 3
	}

	if n, ok := asInt(raw); ok && n >= 1 {
		return n
	}

	return 3
}

// sentinelManifests builds the (asset, statefulset) pair for
// a sentinel-mode redis resource. Mirrors the structure
// cmdExpand uses for data-redis emission so the controller's
// dispatcher accepts both shapes uniformly.
//
// Returns the manifests in the order [asset, statefulset] so
// the asset is materialised before the statefulset that mounts
// it on first apply.
//
// Cross-resource state plumbing — fully automatic, zero operator
// gymnastics:
//
//   - env_from = [monitor] inherits the monitor target's entire
//     config bucket (REDIS_PASSWORD, REDIS_MASTER_ORDINAL,
//     REDIS_LINKED_CONSUMERS, etc.). Statefulset env_from is the
//     symmetric pair of the job/cronjob feature — one mechanism,
//     same wire shape. When the data redis rotates its password,
//     the env_from layer flows the new value into the sentinel
//     pods on next reconcile, no extra plumbing.
//   - VOODU_CONTROLLER_URL is auto-injected by the controller's
//     pod env builder for every container, so the entrypoint
//     preflight + failover hook callbacks just work.
func sentinelManifests(req expandRequest, s *sentinelSpec, operatorSpec map[string]any) []manifest {
	replicas := sentinelReplicas(operatorSpec)

	// Merge sentinel-mode defaults under operator overrides.
	// Same merge rules as data-redis path so an operator who
	// declares `image = "redis:8"` or adds an extra volume
	// (e.g., for ACL files referenced by the monitored target)
	// keeps that override intact.
	merged := mergeSpec(composeSentinelDefaults(req.Scope, req.Name), operatorSpec)

	// Strip the sentinel block from the merged spec so it
	// doesn't leak into the statefulset wire shape downstream.
	stripSentinelBlock(merged)

	// env_from = [monitor] makes REDIS_PASSWORD + REDIS_MASTER_ORDINAL
	// flow into the sentinel pods automatically. Operator-declared
	// env_from values (rare in sentinel mode but legal) layer
	// underneath — declared order preserved so the data redis's
	// env wins last (closest to the pod's own env).
	merged["env_from"] = mergeEnvFrom(operatorSpec["env_from"], s.Monitor)

	// Plugin-managed env is the contract surface the entrypoint
	// script reads. Layer it under any operator-declared env so
	// operator-set keys (e.g. VOODU_LOG_LEVEL) coexist.
	merged["env"] = mergeEnv(sentinelPodEnv(s, replicas), merged["env"])

	asset := manifest{
		Kind:  "asset",
		Scope: req.Scope,
		Name:  req.Name,
		Spec: map[string]any{
			"files": map[string]any{
				// Single file: the entrypoint script. The failover
				// hook is embedded inside it (written to disk +
				// chmod +x at boot) — see renderSentinelEntrypointScript
				// for why we don't ship the hook as its own asset
				// (asset bind-mounts come 0644 read-only, Redis
				// refuses non-executable client-reconfig-script).
				sentinelEntrypointAssetKey: renderSentinelEntrypointScript(),
			},
		},
	}

	statefulset := manifest{
		Kind:  "statefulset",
		Scope: req.Scope,
		Name:  req.Name,
		Spec:  merged,
	}

	return []manifest{asset, statefulset}
}

// hasSentinelMonitorRef returns true when the script template
// embeds a sentinel directive — used by tests as a smoke check
// that the renderer hasn't accidentally drifted to a no-op.
func hasSentinelMonitorRef(script string) bool {
	return strings.Contains(script, "sentinel monitor "+sentinelMasterName)
}
